apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: holiday-platform
spec:
  selector:
    app: kafka
  ports:
    - name: host
      port: 9092
      targetPort: 9092
    - name: broker
      port: 29092
      targetPort: 29092
    - name: controller
      port: 29093
      targetPort: 29093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: holiday-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: public.ecr.aws/bitnami/kafka:4.2.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 9092
              name: host
            - containerPort: 29092
              name: broker
            - containerPort: 29093
              name: controller
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "6L8XGfS3T9Wj4e1_L-5_pQ"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS
              value: "kafka:29093"
            - name: KAFKA_INITIAL_CONTROLLERS
              value: "1@kafka:29093:6L8XGfS3T9Wj4e1_L-5_pQ"
            - name: KAFKA_CFG_LISTENERS
              value: "DOCKER://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,HOST://0.0.0.0:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "DOCKER://kafka:29092,HOST://kafka:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "DOCKER"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_COMPRESSION_TYPE
              value: gzip
            - name: KAFKA_CFG_LOG_RETENTION_MS
              value: "-1"
            - name: KAFKA_CFG_LOG_RETENTION_BYTES
              value: "-1"
            - name: KAFKA_CFG_MESSAGE_TIMESTAMP_TYPE
              value: CreateTime
            - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: holiday-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
